# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 51c1d5d0a6d48c6fc3770b71dd693bf40a1725b643bf70ed72025db0f97754c4bf03a2de78b38bba3e992aa1c9213598b1d474212ef08ce70fb28cc6fd18744e

test:
  secret_key_base: fcaca9156afc72a3d989698fb670460d644a482fbdc7ab83c7d485ac94ac5f75b4ffdef484b88e4c626ab9d8d74b2f97507befa9a79cffdafe1ac3a66010c740

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
